# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Volatility3 Memory Analyzer GUI
"""

import os
from pathlib import Path
from PyInstaller.utils.hooks import collect_dynamic_libs, collect_submodules

block_cipher = None

# Get project root directory (same as spec_dir, since build_spec is inside project)
spec_dir = os.path.dirname(os.path.abspath(SPECPATH))
project_root = Path(spec_dir)  # project_root is the directory containing build_spec

# Volatility3 path - it's in a subdirectory
volatility3_path = project_root / "volatility3-2.26.2"
assets_path = project_root / "assets"

crypto_binaries = []
try:
    crypto_binaries = collect_dynamic_libs("Crypto")
except Exception:
    crypto_binaries = []

a = Analysis(
    [str(project_root / "app" / "main.py")],
    pathex=[],
    binaries=crypto_binaries,
    datas=[
        (str(volatility3_path), "volatility3-2.26.2"),
        (str(assets_path), "assets"),
    ],
    hiddenimports=[
        'volatility3',
        'volatility3.framework',
        'volatility3.framework.contexts',
        'volatility3.framework.automagic',
        'volatility3.framework.automagic.windows',
        'volatility3.framework.automagic.linux',
        'volatility3.framework.automagic.mac',
        'volatility3.framework.plugins',
        'volatility3.framework.interfaces',
        'volatility3.framework.interfaces.plugins',
        'volatility3.framework.interfaces.context',
        'volatility3.framework.interfaces.configuration',
        'volatility3.framework.interfaces.renderers',
        'volatility3.framework.interfaces.layers',
        'volatility3.framework.interfaces.objects',
        'volatility3.framework.interfaces.symbols',
        'volatility3.framework.interfaces.automagic',
        'volatility3.framework.layers',
        'volatility3.framework.layers.physical',
        'volatility3.framework.layers.intel',
        'volatility3.framework.symbols',
        'volatility3.framework.symbols.windows',
        'volatility3.cli',
        'volatility3.cli.text_renderer',
        'volatility3.cli.volargparse',
        'volatility3.cli.text_filter',
        'volatility3.plugins',
        'volatility3.plugins.windows',
        'volatility3.plugins.windows.pslist',
        'volatility3.plugins.windows.netscan',
        'volatility3.symbols',
        'volatility3.schemas',
        'battle_cli',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        # Standard library modules that might be missing
        'glob',
        'fnmatch',
        'pathlib',
        'collections',
        'collections.abc',
        'typing',
        'typing_extensions',
        'sqlite3',
        'json',
        'hashlib',
        'zlib',
        'gzip',
        'pickle',
        'struct',
        'io',
        'os',
        'sys',
        'logging',
        're',
        'urllib',
        'urllib.parse',
        'urllib.request',
        'base64',
        'binascii',
        'uuid',
        'datetime',
        'time',
        'calendar',
        'email',
        'email.utils',
        'http',
        'http.client',
        'socket',
        'threading',
        'multiprocessing',
        'queue',
        'tempfile',
        'shutil',
        'copy',
        'itertools',
        'functools',
        'operator',
        'weakref',
        'gc',
        'ctypes',
        'ctypes.util',
        'ipaddress',
        'netaddr',
        'yara',
        'capstone',
        'pefile',
        'Crypto',
        'Crypto.Cipher',
        'Crypto.Hash',
        'zipfile',
        'tarfile',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'html',
        'html.parser',
        'csv',
        'configparser',
        'argparse',
        'inspect',
        'traceback',
        'warnings',
        'importlib',
        'importlib.util',
        'importlib.metadata',
        'pkgutil',
        'pkg_resources',
        # Additional standard library modules
        'abc',
        'bisect',
        'bz2',
        'codecs',
        'contextlib',
        'dataclasses',
        'enum',
        'lzma',
        'math',
        'numbers',
        'random',
        'secrets',
        'string',
        'textwrap',
        'unicodedata',
        'locale',
        'platform',
        'subprocess',
        'signal',
        'errno',
        'stat',
        'posixpath',
        'ntpath',
        'mmap',
        'array',
    ] + collect_submodules('Crypto'),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Volatility3Analyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Required for integrated Battle CLI terminal I/O
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(assets_path / "account.png") if (assets_path / "account.png").exists() else None,
)

